/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldiersRouteImport } from './routes/soldiers'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'

const SoldiersRoute = SoldiersRouteImport.update({
  id: '/soldiers',
  path: '/soldiers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/laws': typeof LawsRoute
  '/leadership': typeof LeadershipRoute
  '/operations': typeof OperationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/soldiers': typeof SoldiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/laws': typeof LawsRoute
  '/leadership': typeof LeadershipRoute
  '/operations': typeof OperationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/soldiers': typeof SoldiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/laws': typeof LawsRoute
  '/leadership': typeof LeadershipRoute
  '/operations': typeof OperationsRoute
  '/recruitment': typeof RecruitmentRoute
  '/soldiers': typeof SoldiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/laws'
    | '/leadership'
    | '/operations'
    | '/recruitment'
    | '/soldiers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/laws'
    | '/leadership'
    | '/operations'
    | '/recruitment'
    | '/soldiers'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/laws'
    | '/leadership'
    | '/operations'
    | '/recruitment'
    | '/soldiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  LawsRoute: typeof LawsRoute
  LeadershipRoute: typeof LeadershipRoute
  OperationsRoute: typeof OperationsRoute
  RecruitmentRoute: typeof RecruitmentRoute
  SoldiersRoute: typeof SoldiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soldiers': {
      id: '/soldiers'
      path: '/soldiers'
      fullPath: '/soldiers'
      preLoaderRoute: typeof SoldiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  LawsRoute: LawsRoute,
  LeadershipRoute: LeadershipRoute,
  OperationsRoute: OperationsRoute,
  RecruitmentRoute: RecruitmentRoute,
  SoldiersRoute: SoldiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
